### ISSUE TITLE
Why running so long?

### ISSUE THREAD

**Issue by donghaoye** [CharlesShang/FastMaskRCNN#101]

**Comment by kevinkit** [comment]
This was adressed in other issues before, please read them before comming up with new issues, to prevent overflow.

Anyhow the answer is:

This is adressed in the original paper of the the Mask RCNN. They trained for 2 days on a 8 GPU machine. Since parallelism does not speed up linear this may take this long. Even if it'd be linear it would be 16 days on a single GPU. This was done on the COCO dataset so other datasets may differ. Since you can increase the Batchsize much higher the more memory you have available (which would be 8 times higher with 8 GPUs) the CUDA-Stream applications will increase the heterogenous tasks, which will result in a shorter training time.

Like discussed in:  #31
